"""
Incident Reporter
Generates structured markdown + JSON incident reports.
Saves to disk and stores path in MongoDB.
"""
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from app.models.schemas import Incident, IncidentStatus
from app.utils.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

REPORTS_DIR = Path(settings.REPORTS_DIR)
REPORTS_DIR.mkdir(exist_ok=True)


class IncidentReporter:
    def generate(self, incident: Incident) -> str:
        """Generate markdown report, save to disk, return file path."""
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"{incident.incident_id}_{ts}.md"
        path = REPORTS_DIR / filename

        md = self._build_markdown(incident)
        path.write_text(md)

        # Also save JSON sidecar
        json_path = path.with_suffix(".json")
        json_path.write_text(incident.model_dump_json(indent=2))

        logger.info(f"📄 Report saved: {path}")
        return str(path)

    def _emoji_status(self, status: IncidentStatus) -> str:
        return {
            IncidentStatus.RESOLVED: "✅",
            IncidentStatus.ESCALATED: "🚨",
            IncidentStatus.FAILED: "❌",
        }.get(status, "⏳")

    def _build_markdown(self, inc: Incident) -> str:
        d = inc.diagnosis
        r = inc.remediation
        v = inc.verification

        duration = ""
        if inc.resolved_at and inc.created_at:
            secs = (inc.resolved_at - inc.created_at).total_seconds()
            duration = f"{int(secs // 60)}m {int(secs % 60)}s"

        lines = [
            f"# {self._emoji_status(inc.status)} Incident Report — {inc.incident_id}",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| **Status** | {inc.status.upper()} |",
            f"| **Service** | `{inc.service}` |",
            f"| **Type** | {inc.incident_type} |",
            f"| **Severity** | {inc.severity.upper()} |",
            f"| **Detected** | {inc.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')} |",
            f"| **Resolved** | {inc.resolved_at.strftime('%Y-%m-%d %H:%M:%S UTC') if inc.resolved_at else 'N/A'} |",
            f"| **Duration** | {duration or 'N/A'} |",
            f"| **Confidence** | {d.confidence:.0%} |" if d else "",
            "",
            "## 🔍 Root Cause",
            "",
            d.root_cause if d else "_Not diagnosed_",
            "",
            "## 🧠 AI Reasoning",
            "",
            d.reasoning if d else "_No LLM reasoning available_",
            "",
            "## 📊 Evidence",
            "",
        ]

        if inc.signal:
            for k, v_val in inc.signal.evidence.items():
                lines.append(f"- **{k}**: `{v_val}`")
        lines.append("")

        lines += [
            "## ⚙️ Remediation",
            "",
            f"**Action:** `{r.action}`" if r else "_No action taken_",
        ]
        if r:
            lines += [
                f"**Success:** {'✅ Yes' if r.success else '❌ No'}",
                f"**Duration:** {r.duration_seconds}s",
                f"**Output:** {r.output}",
            ]
        lines.append("")

        lines += [
            "## ✅ Verification",
            "",
        ]
        if v:
            lines.append(f"**Healthy:** {'✅ Yes' if v.healthy else '❌ No'}")
            lines.append(f"**Message:** {v.message}")
            if v.checks:
                lines.append("")
                lines.append("**Health Checks:**")
                for check, passed in v.checks.items():
                    lines.append(f"- {'✅' if passed else '❌'} `{check}`")
        else:
            lines.append("_Not verified_")

        lines += [
            "",
            "## 📅 Timeline",
            "",
        ]
        for event in inc.timeline:
            ts_str = event.get("timestamp", "")
            msg = event.get("message", "")
            lines.append(f"- `{ts_str}` — {msg}")

        lines += [
            "",
            "---",
            f"_Generated by AI Incident Agent at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}_",
        ]

        return "\n".join(lines)
